# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tenseal_allreduce_data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1ctenseal_allreduce_data.proto\".\n\nclient_msg\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\x0c\x32\x37\n\x10\x41llReduceService\x12#\n\x07sum_enc\x12\x0b.client_msg\x1a\x0b.client_msgb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tenseal_allreduce_data_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CLIENT_MSG']._serialized_start=32
  _globals['_CLIENT_MSG']._serialized_end=78
  _globals['_ALLREDUCESERVICE']._serialized_start=80
  _globals['_ALLREDUCESERVICE']._serialized_end=135
# @@protoc_insertion_point(module_scope)
