# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transmission.tenseal_shapley.tenseal_allreduce_data_pb2 as tenseal__allreduce__data__pb2


class AllReduceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sum_enc = channel.unary_unary(
                '/AllReduceService/sum_enc',
                request_serializer=tenseal__allreduce__data__pb2.client_msg.SerializeToString,
                response_deserializer=tenseal__allreduce__data__pb2.client_msg.FromString,
                )


class AllReduceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def sum_enc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AllReduceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sum_enc': grpc.unary_unary_rpc_method_handler(
                    servicer.sum_enc,
                    request_deserializer=tenseal__allreduce__data__pb2.client_msg.FromString,
                    response_serializer=tenseal__allreduce__data__pb2.client_msg.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AllReduceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AllReduceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def sum_enc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AllReduceService/sum_enc',
            tenseal__allreduce__data__pb2.client_msg.SerializeToString,
            tenseal__allreduce__data__pb2.client_msg.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
